# Generated by Django 5.1.1 on 2024-11-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglage',
            name='deuxieme_vitesse',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='premiere_vitesse',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='rapport_final',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
