# Generated by Django 5.1.1 on 2024-10-27 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(choices=[('Abarth', 'Abarth'), ('AC', 'AC'), ('Alpha Romeo', 'Alpha Romeo'), ('Alpine', 'Alpine'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Caterham', 'Caterham'), ('Chevrolet', 'Chevrolet'), ('Citroen', 'Citroen'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Jaguar', 'Jaguar'), ('Koenlgsegg', 'Koenlgsegg'), ('Lamborghini', 'Lamborghini'), ('Lancia', 'Lancia'), ('Lotus', 'Lotus'), ('McLaren', 'McLaren'), ('Mercedes-AMG', 'Mercedes-AMG'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Nissan', 'Nissan'), ('Porshe', 'Porshe'), ('Shelby', 'Shelby'), ('Sientero', 'Sientero'), ('WMotors', 'WMotors'), ('Wolkwagen', 'Wolkswagen')], max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('RWD', 'RWD'), ('FWD', 'FWD'), ('4WD', '4WD')], max_length=3)),
                ('indice', models.PositiveIntegerField()),
                ('ip', models.PositiveIntegerField()),
                ('categorie', models.CharField(choices=[('A', 'Catégorie A'), ('B', 'Catégorie B'), ('C', 'Catégorie C'), ('D', 'Catégorie D'), ('E', 'Catégorie E'), ('F', 'Catégorie F'), ('G', 'Catégorie G'), ('H', 'Catégorie H')], max_length=1)),
                ('rarete', models.CharField(blank=True, choices=[('légendaire', 'Légendaire'), ('épique', 'Épique'), ('rare', 'Rare'), ('commun', 'Commun'), ('peu commun', 'Peu commun'), (None, 'Aucune')], max_length=10, null=True)),
                ('prix_initial', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_prix', to='tduscmap.car')),
            ],
        ),
    ]
