# Generated by Django 5.1.1 on 2024-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglage',
            name='acceleration_arriere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='deceleration_arriere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='freinage_arriere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
