# Generated by Django 5.1.1 on 2024-11-15 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0002_alter_configurationreglage_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom ou description du trajet', max_length=100)),
                ('depart_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('depart_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('etapes', models.JSONField(help_text='Liste des points intermédiaires sous forme de latitude/longitude')),
                ('arrivee_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('arrivee_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
