# Generated by Django 5.1.1 on 2024-11-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0002_alter_car_marque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reglage',
            old_name='voiture',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='reglage',
            old_name='utilisateur',
            new_name='user_id',
        ),
    ]
