# Generated by Django 5.1.1 on 2024-10-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0002_car_carprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='indice',
        ),
    ]
