# Generated by Django 5.1.1 on 2024-11-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0002_alter_reglage_deuxieme_vitesse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
