# Generated by Django 5.1.1 on 2024-12-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0003_alter_reglage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglage',
            name='durete_barre_antiroulis_arriere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='durete_barre_antiroulis_avant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='pression_freinage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='repartiteur_freinage_avant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
