# Generated by Django 5.1.1 on 2024-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0003_alter_reglage_acceleration_avant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationreglage',
            name='troisieme_vitesse_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='troisieme_vitesse_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
