# Generated by Django 5.1.1 on 2024-11-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0003_rename_voiture_reglage_car_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reglage',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='reglage',
            old_name='user_id',
            new_name='user',
        ),
    ]
