# Generated by Django 5.1.1 on 2024-11-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0003_trajet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='arrivee_lat',
            field=models.FloatField(help_text="Coordonnée Y en pixels du point d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='arrivee_lng',
            field=models.FloatField(help_text="Coordonnée X en pixels du point d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart_lat',
            field=models.FloatField(help_text='Coordonnée Y en pixels du point de départ'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart_lng',
            field=models.FloatField(help_text='Coordonnée X en pixels du point de départ'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='etapes',
            field=models.JSONField(help_text='Liste des points intermédiaires sous forme de coordonnées pixels'),
        ),
    ]
