# Generated by Django 5.1.1 on 2024-11-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0004_alter_trajet_arrivee_lat_alter_trajet_arrivee_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.IntegerField()),
                ('category', models.CharField(choices=[('solarCoins', 'Solar Coins'), ('clan', 'Clan'), ('reputation', 'Réputation'), ('epave', 'Épave'), ('epave2', 'Épave 2'), ('concessionaire', 'Concessionnaire'), ('station', 'Station'), ('atelier', 'Atelier'), ('rassemblement', 'Rassemblement')], max_length=20)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
