# Generated by Django 5.1.1 on 2024-12-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0004_alter_reglage_durete_barre_antiroulis_arriere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='categorie',
            field=models.CharField(choices=[('A', 'Catégorie A'), ('B', 'Catégorie B'), ('C', 'Catégorie C'), ('D', 'Catégorie D'), ('E', 'Catégorie E'), ('F', 'Catégorie F'), ('G', 'Catégorie G'), ('S', 'Catégorie S'), ('H', 'Catégorie H')], max_length=1, null=True),
        ),
    ]
