# Generated by Django 5.1.1 on 2024-11-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0004_alter_configurationreglage_troisieme_vitesse_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglage',
            name='troisieme_vitesse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
