# Generated by Django 5.1.1 on 2024-11-06 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0005_alter_reglage_angle_carrossage_arriere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglage',
            name='compression_amortisseurs_arriere',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='compression_amortisseurs_avant',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='decompression_amortisseurs_arriere',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='decompression_amortisseurs_avant',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='durete_ressorts_arriere',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='reglage',
            name='durete_ressorts_avant',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
