# Generated by Django 5.1.1 on 2024-11-25 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0005_mapelement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapElement',
        ),
        migrations.AddField(
            model_name='car',
            name='nb_vitesse',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
