# Generated by Django 5.1.1 on 2024-11-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0005_alter_reglage_troisieme_vitesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationreglage',
            name='taille_suspension_arriere_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='taille_suspension_arriere_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='taille_suspension_avant_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='taille_suspension_avant_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
