# Generated by Django 5.1.1 on 2024-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0006_delete_mapelement_car_nb_vitesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglage',
            name='dixieme_vitesse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reglage',
            name='neuvieme_vitesse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
