# Generated by Django 5.1.1 on 2024-12-16 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0007_car_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoriteibiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_ibiza', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trajetibiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom ou description du trajet', max_length=100)),
                ('depart_lat', models.FloatField(help_text='Coordonnée Y en pixels du point de départ')),
                ('depart_lng', models.FloatField(help_text='Coordonnée X en pixels du point de départ')),
                ('etapes', models.JSONField(help_text='Liste des points intermédiaires sous forme de coordonnées pixels')),
                ('arrivee_lat', models.FloatField(help_text="Coordonnée Y en pixels du point d'arrivée")),
                ('arrivee_lng', models.FloatField(help_text="Coordonnée X en pixels du point d'arrivée")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_ibiza', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
