# Generated by Django 5.1.1 on 2024-11-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0009_configurationreglage_acceleration_avant_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationreglage',
            name='acceleration_avant_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='acceleration_centrale_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='deceleration_avant_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='deceleration_centrale_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='distribution_puissance_avant_arriere_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='freinage_avant_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='freinage_central_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='pression_pneus_arriere_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='pression_pneus_avant_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='taille_suspension_arriere_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='taille_suspension_arriere_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='taille_suspension_avant_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='configurationreglage',
            name='taille_suspension_avant_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
