# Generated by Django 5.1.1 on 2024-11-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tduscmap', '0010_alter_configurationreglage_acceleration_avant_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationreglage',
            old_name='freinage_central_max',
            new_name='freinage_centrale_max',
        ),
        migrations.RenameField(
            model_name='configurationreglage',
            old_name='freinage_central_min',
            new_name='freinage_centrale_min',
        ),
    ]
