
version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.3

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_docker_image:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          version: docker23
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/tduscmaps:latest .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/tduscmaps:latest

  deploy:
    machine:
      image: ubuntu-2204:edge
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Render
          command: |
            curl -X POST $HOOK_RENDER \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"image": "docker.io/$DOCKERHUB_USERNAME/tduscmaps:latest", "clearCache": false}'
      
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - build_docker_image:
          requires:
            - build_and_test
      - deploy:
          requires:
            - build_docker_image
          filters:
            branches:
              only: main

