# Generated by Django 5.1.1 on 2024-12-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_reglage_is_active'),
        ('authentication', '0003_auto_20241217_1456'),
    ]

    operations = [
    ]
